name: Update schedule
on:
  workflow_dispatch:
  repository_dispatch:
    types: [openplanner]

jobs:
  update-firestore-session-speakers-schedule:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts/openplanner
    steps:
      - uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: npm run import
        env:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUNNYTECHWEBSITE_FIRESTORE }}
          payloadUrl: ${{ github.event.client_payload.url }}
