name: Update schedule
on:
  workflow_dispatch:
  repository_dispatch:
    types: [openplanner]

jobs:
  update-firestore-session-speakers-schedule:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts/openplanner
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: scripts/openplanner/.nvmrc
          cache: 'npm'
          cache-dependency-path: scripts/openplanner/package-lock.json
      - run: npm ci --ignore-scripts
      - run: npm run import
        env:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUNNYTECHWEBSITE_FIRESTORE }}
          payloadUrl: ${{ github.event.client_payload.url }}
